// Code generated by autodig. DO NOT EDIT.
package app

import (
	dep "github.com/Mafei1024/autodig/dep"
)

func app_NewObject() Object {
	return NewObject()
}
func init() {
	dep.MustProvide([]interface {
	}{app_NewObject})
}
