// Code generated by autodig. DO NOT EDIT.
package at

import (
	op1 "github.com/Mafei1024/autodig/demo/app3/op1"
	op2 "github.com/Mafei1024/autodig/demo/app3/op2"
	ser "github.com/Mafei1024/autodig/demo/app3/ser"
	dep "github.com/Mafei1024/autodig/dep"
	dig "go.uber.org/dig"
)

func Newop1Op() (ser.OpI, error) {
	var autoDigErr error
	op := op1.Op{DigReturn: nil}
	return &op, autoDigErr
}
func Newop2Op() (ser.OpI, error) {
	var autoDigErr error
	op := op2.Op{DigReturn: nil}
	return &op, autoDigErr
}
func Newop2Op2() (ser.OpI, error) {
	var autoDigErr error
	op2 := op2.Op2{DigReturn: nil}
	return &op2, autoDigErr
}
func GetSliceBy_Op_Op__2_Op2(param0 struct {
	dig.In
	ser.OpI `name:"Op"`
}, param1 struct {
	dig.In
	ser.OpI `name:"Op__2"`
}, param2 struct {
	dig.In
	ser.OpI `name:"Op2"`
}) []ser.OpI {
	var results []ser.OpI = make([]ser.OpI, 0, 3)
	results = append(results, param0.OpI)
	results = append(results, param1.OpI)
	results = append(results, param2.OpI)
	return results
}
func init() {
	dep.MustProvide([]interface {
	}{Newop1Op}, dig.Name("Op"))
	dep.MustProvide([]interface {
	}{Newop2Op}, dig.Name("Op__2"))
	dep.MustProvide([]interface {
	}{Newop2Op2}, dig.Name("Op2"))
	dep.MustProvide([]interface {
	}{GetSliceBy_Op_Op__2_Op2})
}
