// Code generated by autodig. DO NOT EDIT.
package demo

import (
	dep "github.com/Mafei1024/autodig/dep"
	dig "go.uber.org/dig"
)

func demo_NewControllerDemo5() ControllerI {
	return NewControllerDemo5()
}
func demo_NewAbGrpcClient() *GrpcClient {
	return NewAbGrpcClient()
}
func NewdemoMy() (Me, error) {
	var autoDigErr error
	my := My{DigReturn: nil}
	return &my, autoDigErr
}
func NewdemoB(SS []Self, demoBParam struct {
	dig.In
	S Self `name:"S1"`
}) (*B, error) {
	var autoDigErr error
	b := B{SS: SS, S: demoBParam.S}
	return &b, autoDigErr
}
func demo_NewGrpcClient() *GrpcClient {
	return NewGrpcClient()
}
func NewdemoService(GrpcClient *GrpcClient, demoServiceParam struct {
	dig.In
	AbGrpcClient *GrpcClient `name:"abGrpcClient"`
}) (*Service, error) {
	var autoDigErr error
	service := Service{GrpcClient: GrpcClient, AbGrpcClient: demoServiceParam.AbGrpcClient}
	return &service, autoDigErr
}
func NewdemoS2() (Self, error) {
	var autoDigErr error
	s2 := S2{DigReturn: nil}
	return &s2, autoDigErr
}
func demo_NewS2() Self {
	return NewS2()
}
func NewdemoControllerDemo3() (ControllerI, error) {
	var autoDigErr error
	controllerdemo3 := ControllerDemo3{DigReturn: nil}
	return &controllerdemo3, autoDigErr
}
func demo_NewControllerDemo4() ControllerI {
	return NewControllerDemo4()
}
func NewdemoS1() (Self, error) {
	var autoDigErr error
	s1 := S1{DigReturn: nil}
	return &s1, autoDigErr
}
func demo_NewS1() Self {
	return NewS1()
}
func NewdemoControllerDemo1() (ControllerI, error) {
	var autoDigErr error
	controllerdemo1 := ControllerDemo1{DigReturn: nil}
	return &controllerdemo1, autoDigErr
}
func NewdemoControllerDemo2() (ControllerI, error) {
	var autoDigErr error
	controllerdemo2 := ControllerDemo2{DigReturn: nil}
	return &controllerdemo2, autoDigErr
}
func NewS1_S2_NewS1_NewS2_All(param0 struct {
	dig.In
	Self `name:"S1"`
}, param1 struct {
	dig.In
	Self `name:"S2"`
}, param2 struct {
	dig.In
	Self `name:"NewS1"`
}, param3 struct {
	dig.In
	Self `name:"NewS2"`
}) ([]Self, error) {
	var results []Self = make([]Self, 0, 4)
	results = append(results, param0)
	results = append(results, param1)
	results = append(results, param2)
	results = append(results, param3)
	return results, nil
}
func NewControllerDemo1_ControllerDemo2_cd3_NewControllerDemo4_ncd5_All(param0 struct {
	dig.In
	ControllerI `name:"ControllerDemo1"`
}, param1 struct {
	dig.In
	ControllerI `name:"ControllerDemo2"`
}, param2 struct {
	dig.In
	ControllerI `name:"cd3"`
}, param3 struct {
	dig.In
	ControllerI `name:"NewControllerDemo4"`
}, param4 struct {
	dig.In
	ControllerI `name:"ncd5"`
}) ([]ControllerI, error) {
	var results []ControllerI = make([]ControllerI, 0, 5)
	results = append(results, param0)
	results = append(results, param1)
	results = append(results, param2)
	results = append(results, param3)
	results = append(results, param4)
	return results, nil
}
func NewMy_All(param Me) ([]Me, error) {
	var results []Me = make([]Me, 0, 1)
	results = append(results, param)
	return results, nil
}
func init() {
	dep.MustProvide([]interface {
	}{NewdemoS1}, dig.Name("S1"))
	dep.MustProvide([]interface {
	}{NewdemoControllerDemo1}, dig.Name("ControllerDemo1"))
	dep.MustProvide([]interface {
	}{demo_NewS2}, dig.Name("NewS2"))
	dep.MustProvide([]interface {
	}{demo_NewAbGrpcClient}, dig.Name("abGrpcClient"))
	dep.MustProvide([]interface {
	}{NewdemoMy, NewdemoB, demo_NewGrpcClient, NewdemoService, NewS1_S2_NewS1_NewS2_All, NewControllerDemo1_ControllerDemo2_cd3_NewControllerDemo4_ncd5_All, NewMy_All})
	dep.MustProvide([]interface {
	}{NewdemoS2}, dig.Name("S2"))
	dep.MustProvide([]interface {
	}{NewdemoControllerDemo3}, dig.Name("cd3"))
	dep.MustProvide([]interface {
	}{demo_NewControllerDemo4}, dig.Name("NewControllerDemo4"))
	dep.MustProvide([]interface {
	}{demo_NewS1}, dig.Name("NewS1"))
	dep.MustProvide([]interface {
	}{NewdemoControllerDemo2}, dig.Name("ControllerDemo2"))
	dep.MustProvide([]interface {
	}{demo_NewControllerDemo5}, dig.Name("ncd5"))
}
