dig1:
	go get github.com/Mafei1024/autodig
	go install github.com/Mafei1024/autodig
	$(GOPATH)/bin/autodig -scans ./app1 -output ./app1/autodig.go

dig2:
	go get github.com/Mafei1024/autodig
	go install github.com/Mafei1024/autodig
	$(GOPATH)/bin/autodig -samename -scans ./app2 -output ./app2/autodig.go

help:
	go get github.com/Mafei1024/autodig
	go install github.com/Mafei1024/autodig
	$(GOPATH)/bin/autodig -help